### ISSUE TITLE
Random seed

### ISSUE THREAD

**Issue by PotatoBananaApple** [WASasquatch/PPF_Noise_ComfyUI#1]
Using random seed is giving me this error 
![image](https://github.com/WASasquatch/PPF_Noise_ComfyUI/assets/130109414/75531f59-0e5a-42a7-8207-19f6cacbc044)

Works if seed is fixed to lower value

**Comment by WASasquatch** [comment]
Yeah, ComfyUI seeds are extremely high, higher then `sys.maxsize` I think which is not good. As a lot of software can't seeds so large. Not even PyTorch suggests such large seeds for inference. 

If I scale the seed, I'd have to output it to the console, and hope the user makes no of it. I think for now it's better to have them manually pick a sane seed size. I really wish Comfy wouldn't use such large seeds but he isn't really concerned about other things using it.

**Comment by WASasquatch** [comment]
Decided to trim seed instead.
